services:
  db-diary:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ./.env.dev
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
    - db-blog-network

  pgAdmin-diary:
    image: dpage/pgadmin4:8.14
    env_file:
      - ./.env.dev
    container_name: ${PGADMIN_CONTAINER_NAME}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db-diary
    networks:
      - db-blog-network
networks:
  db-blog-network:
    driver: bridge
